language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "node"
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - yarn test
    - stage: build
      script:
        - yarn build
